settings:
  hide: true
  content:
    merge: true

# Media configuration
media:
  input: src/assets/images
  output: /assets/images

# Content configuration
content:
  # Main Pages Collection (navigation items)
  - name: pages
    label: Pages
    type: collection
    path: src/pages
    filter:
      field: nav_item
      value: true
    view:
      fields: [nav_title, order, title]
      sort:
        field: order
        direction: asc
    fields:
      - name: title
        label: Title
        type: string
        required: true
        description: Full page title (used in browser tab and SEO)

      - name: description
        label: Description
        type: string
        required: true
        description: Page description for SEO

      - name: layout
        label: Layout
        type: string
        description: Template layout file (e.g., home.html, contact.html, services.html)

      - name: permalink
        label: Permalink
        type: string
        description: Custom URL path (e.g., /, /not_found.html)

      - name: nav_item
        label: Show in Navigation
        type: boolean
        default: true
        description: Display this page in the main navigation menu

      - name: nav_title
        label: Navigation Title
        type: string
        required: true
        description: Short title displayed in navigation menu

      - name: order
        label: Order
        type: number
        required: true
        description: Display order in navigation (lower numbers appear first)

      - name: heading_text
        label: Heading Text
        type: string
        description: Alternative heading text (optional, overrides title)

      - name: services_heading
        label: Services Section Heading
        type: string
        description: Heading for the services grid section

      - name: services_intro
        label: Services Introduction
        type: rich-text
        description: Introduction text before the service list

      - name: contact_text
        label: Contact Text
        type: rich-text
        description: Contact information displayed at bottom of page

      - name: body
        label: Body
        type: rich-text
        description: Main page content

  - name: services
    label: Services
    type: collection
    path: src/services
    filter:
      field: tags
      value: service
    view:
      fields: [nav_title, order, title]
      sort:
        field: order
        direction: asc
    fields:
      - name: title
        label: Title
        type: string
        required: true
        description: Full page title (used in browser tab and SEO)

      - name: description
        label: Description
        type: string
        required: true
        description: Page description for SEO

      - name: tags
        label: Tags
        type: string
        default: service
        required: true
        description: Content tag (should be "service" for service pages)

      - name: nav_title
        label: Service Name
        type: string
        required: true
        description: Service name displayed in navigation

      - name: order
        label: Order
        type: number
        required: true
        description: Display order (lower numbers appear first)

      - name: thumb
        label: Thumbnail Image
        type: image
        required: true
        description: Thumbnail image for service card

      - name: body
        label: Body
        type: rich-text
        description: Service page content
